# Generated by Django 2.2.12 on 2020-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта, должно быть уникальным', max_length=50, unique=True, verbose_name='Наименование')),
                ('customer', models.CharField(max_length=50, verbose_name='Заказчик')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('description', models.TextField(help_text='Заметки, чтобы не забыть', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
