# Generated by Django 2.2.12 on 2020-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Заметки, чтобы не забыть', null=True, verbose_name='Описание'),
        ),
    ]
