# Generated by Django 2.2.12 on 2020-04-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0003_auto_20200414_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', help_text='Заметки, чтобы не забыть', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФИО')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', help_text='Примечание', verbose_name='Описание')),
                ('job', models.ForeignKey(help_text='Работа, которую выполняет данный работник', on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='bala.Job', verbose_name='Работа')),
            ],
        ),
    ]
