# Generated by Django 2.2.12 on 2020-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0004_job_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Дата')),
                ('project', models.CharField(max_length=50, verbose_name='Проект')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Поступления',
            },
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Дата')),
                ('project', models.CharField(max_length=50, verbose_name='Проект')),
                ('Worker', models.CharField(max_length=100, unique=True, verbose_name='ФИО Работника')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Расходы',
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
