# Generated by Django 2.2.12 on 2020-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0005_auto_20200414_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes',
            options={'verbose_name': 'Поступления', 'verbose_name_plural': 'Поступления'},
        ),
        migrations.AlterModelOptions(
            name='outcomes',
            options={'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterField(
            model_name='incomes',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
