# Generated by Django 2.2.12 on 2020-04-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0006_auto_20200414_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcomes',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='price',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='outcomes',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='outcomes',
            old_name='price',
            new_name='sum',
        ),
    ]
