# Generated by Django 2.2.12 on 2020-04-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0007_auto_20200414_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='bala.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bala.Job', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='bala.Project', verbose_name='Проект'),
        ),
    ]
