# Generated by Django 2.2.12 on 2020-04-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0008_auto_20200414_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomes',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bala.Worker', verbose_name='Работник'),
        ),
    ]
