# Generated by Django 2.2.12 on 2020-04-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0009_auto_20200414_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Объем')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Сумма')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='bala.Project', verbose_name='Проект')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='bala.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
    ]
