# Generated by Django 2.2.12 on 2020-04-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0012_auto_20200429_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
